site_name: "Meu SUS Digital"
site_url: "https://requisitos-de-software.github.io/2024.2-MeuSUSDigital/"
theme:
  name: "material"
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
  logo: imagens/meu-sus-digital-icone.png
 
nav:

  - Home: index.md
  - Apresentação:
    - Apresentação 01: apresentacao/apresentacao01.md
    - Apresentação 02: apresentacao/apresentacao02.md
    - Apresentação 03: apresentacao/apresentacao03.md
  - Atas:
    - Ata 01: atas/ata01.md
    - Ata 02: atas/ata02.md
    - Ata 03: atas/ata03.md
    - Ata 04: atas/ata04.md
    - Ata 05: atas/ata05.md
  - Pré-Rastreabilidade:
    - Rich Picture: pre-rastreabilidade/rich-picture.md
  - Planejamento:
    - HeatMap: planejamento/heatmap.md
    - Ferramentas: planejamento/ferramentas.md
    - Cronograma de Planejamento: planejamento/cronograma-planejamento.md
    - Cronograma de Execução: planejamento/cronograma-execucao.md
    - Aplicativos Avaliados: planejamento/apps-avaliados.md
    - Aplicativo Selecionado: planejamento/app-selecionado.md
    - Termo de Uso: planejamento/termo-de-uso.md
  - Elicitação:
    - Análise de Perfil de Usuário:
      - Perfil de Usuário: elicitacao/analise-perfil-usuario/perfil-usuario.md
      - Questionário: elicitacao/analise-perfil-usuario/questionario.md
    - Planejamento:
      - Cronograma de Elicitação de Requisitos: elicitacao/planejamento/cronograma-tecnicas.md
      - Cronograma de Priorização de Requisitos: elicitacao/planejamento/cronograma-priorizacao.md
    - Técnicas: 
      - Análise de Documentos: elicitacao/tecnicas/analise-de-documentos.md
      - Observação: elicitacao/tecnicas/observacao.md
      - Introspecção: elicitacao/tecnicas/introspeccao.md
      - Entrevista: elicitacao/tecnicas/entrevista.md
      - Grupo de Foco: elicitacao/tecnicas/grupo-de-foco.md
    - Priorização: 
      - $100: elicitacao/priorizacao/$100.md
      - Matriz GUT: elicitacao/priorizacao/matriz-gut.md
    - Requisitos Elicitados: elicitacao/requisitos-elicitados.md
  - Modelagem:
    - Cenários: modelagem/cenarios.md
    - Léxicos: modelagem/lexicos.md
    - Caso de Uso: modelagem/caso-de-uso.md
    - Especificação Suplementar: modelagem/especificacao-suplementar.md
  - Modelagem ─ Ágil:
    - Histórias de Usuário: modelagem-agil/historias-de-usuario.md
    - NFR Framework: modelagem-agil/nfr-framework.md
    - Backlog: modelagem-agil/backlog.md
  - Verificação:
    - Lista de Verificação:
      - Entrega 1: verificacao/lista_verif/entrega1.md
      - Entrega 2: verificacao/lista_verif/entrega2.md
      - Entrega 3: verificacao/lista_verif/entrega3.md
    - Inspeções do Grupo 4:
      - Entrega 1: verificacao/grupo4/entrega1/entrega1.md
      - Entrega 2: verificacao/grupo4/entrega1/entrega2.md
      - Entrega 3: verificacao/grupo4/entrega1/entrega3.md
    - Inspeções do Grupo 5:
      - Entrega 1: verificacao/grupo5/entrega1/entrega1g5.md
      - Entrega 2: verificacao/grupo5/entrega1/entrega2g5.md
      - Entrega 3: verificacao/grupo5/entrega1/entrega3g5.md
